INSERT INTO Flights (departure, arrival, duration_hours) VALUES
('FRA (Frankfurt am Main Airport)', 'CDG (Paris Charles de Gaulle)', 2.1),
('CDG (Paris Charles de Gaulle)', 'ORY (Paris Orly)', 1.7),
('FRA (Frankfurt am Main Airport)', 'CDG (Paris Charles de Gaulle)', 3.1),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 3.3),
('SIN (Singapore Changi Airport)', 'LHR (London Heathrow)', 1.5),
('MAD (Madrid Barajas Airport)', 'ORY (Paris Orly)', 3.1),
('DXB (Dubai International Airport)', 'SIN (Singapore Changi Airport)', 1.8),
('MAD (Madrid Barajas Airport)', 'AMS (Amsterdam Schiphol)', 1.5),
('DXB (Dubai International Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 2.9),
('FRA (Frankfurt am Main Airport)', 'LHR (London Heathrow)', 2.4),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 2.0),
('JFK (New York John F. Kennedy)', 'SIN (Singapore Changi Airport)', 2.7),
('FRA (Frankfurt am Main Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.0),
('DXB (Dubai International Airport)', 'MAD (Madrid Barajas Airport)', 2.3),
('MAD (Madrid Barajas Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 1.6),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 1.5),
('DXB (Dubai International Airport)', 'ORY (Paris Orly)', 1.3),
('CDG (Paris Charles de Gaulle)', 'MAD (Madrid Barajas Airport)', 3.6),
('JFK (New York John F. Kennedy)', 'CDG (Paris Charles de Gaulle)', 2.3),
('AMS (Amsterdam Schiphol)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.6),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 2.4),
('SIN (Singapore Changi Airport)', 'FRA (Frankfurt am Main Airport)', 3.5),
('MAD (Madrid Barajas Airport)', 'ORY (Paris Orly)', 1.5),
('MAD (Madrid Barajas Airport)', 'FRA (Frankfurt am Main Airport)', 2.3),
('AMS (Amsterdam Schiphol)', 'MAD (Madrid Barajas Airport)', 1.6),
('ORY (Paris Orly)', 'LHR (London Heathrow)', 1.2),
('CDG (Paris Charles de Gaulle)', 'ORY (Paris Orly)', 3.4),
('SIN (Singapore Changi Airport)', 'LHR (London Heathrow)', 1.4),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 3.4),
('FRA (Frankfurt am Main Airport)', 'AMS (Amsterdam Schiphol)', 3.5),
('AMS (Amsterdam Schiphol)', 'FRA (Frankfurt am Main Airport)', 1.4),
('MAD (Madrid Barajas Airport)', 'SIN (Singapore Changi Airport)', 2.6),
('CDG (Paris Charles de Gaulle)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 2.8),
('JFK (New York John F. Kennedy)', 'MAD (Madrid Barajas Airport)', 3.9),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 3.3),
('CDG (Paris Charles de Gaulle)', 'DXB (Dubai International Airport)', 1.2),
('CDG (Paris Charles de Gaulle)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.2),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 3.7),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'AMS (Amsterdam Schiphol)', 1.4),
('DXB (Dubai International Airport)', 'AMS (Amsterdam Schiphol)', 3.3),
('JFK (New York John F. Kennedy)', 'AMS (Amsterdam Schiphol)', 2.2),
('AMS (Amsterdam Schiphol)', 'SIN (Singapore Changi Airport)', 2.5),
('MAD (Madrid Barajas Airport)', 'DXB (Dubai International Airport)', 3.1),
('SIN (Singapore Changi Airport)', 'MAD (Madrid Barajas Airport)', 1.1),
('ORY (Paris Orly)', 'SIN (Singapore Changi Airport)', 2.9),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 3.5),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 1.7),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 1.7),
('MAD (Madrid Barajas Airport)', 'ORY (Paris Orly)', 1.5),
('CDG (Paris Charles de Gaulle)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 2.8),
('FRA (Frankfurt am Main Airport)', 'DXB (Dubai International Airport)', 2.7),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'LHR (London Heathrow)', 1.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 3.9),
('SIN (Singapore Changi Airport)', 'LHR (London Heathrow)', 1.6),
('ORY (Paris Orly)', 'CDG (Paris Charles de Gaulle)', 3.4),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 1.1),
('JFK (New York John F. Kennedy)', 'SIN (Singapore Changi Airport)', 1.9),
('JFK (New York John F. Kennedy)', 'DXB (Dubai International Airport)', 1.9),
('JFK (New York John F. Kennedy)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.5),
('JFK (New York John F. Kennedy)', 'SIN (Singapore Changi Airport)', 3.1),
('AMS (Amsterdam Schiphol)', 'SIN (Singapore Changi Airport)', 3.8),
('JFK (New York John F. Kennedy)', 'AMS (Amsterdam Schiphol)', 3.3),
('LHR (London Heathrow)', 'SIN (Singapore Changi Airport)', 3.6),
('FRA (Frankfurt am Main Airport)', 'CDG (Paris Charles de Gaulle)', 3.0),
('LHR (London Heathrow)', 'ORY (Paris Orly)', 3.7),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 2.7),
('FRA (Frankfurt am Main Airport)', 'LHR (London Heathrow)', 2.6),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 3.6),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 3.4),
('JFK (New York John F. Kennedy)', 'FRA (Frankfurt am Main Airport)', 2.8),
('FRA (Frankfurt am Main Airport)', 'CDG (Paris Charles de Gaulle)', 3.6),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 2.7),
('JFK (New York John F. Kennedy)', 'DXB (Dubai International Airport)', 1.7),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 2.7),
('AMS (Amsterdam Schiphol)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 2.2),
('AMS (Amsterdam Schiphol)', 'LHR (London Heathrow)', 1.3),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'LHR (London Heathrow)', 1.2),
('JFK (New York John F. Kennedy)', 'ORY (Paris Orly)', 1.7),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'MAD (Madrid Barajas Airport)', 2.7),
('LHR (London Heathrow)', 'ORY (Paris Orly)', 1.8),
('MAD (Madrid Barajas Airport)', 'DXB (Dubai International Airport)', 1.7),
('SIN (Singapore Changi Airport)', 'LHR (London Heathrow)', 3.3),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 2.0),
('FRA (Frankfurt am Main Airport)', 'DXB (Dubai International Airport)', 3.0),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 3.2),
('CDG (Paris Charles de Gaulle)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 1.5),
('SIN (Singapore Changi Airport)', 'FRA (Frankfurt am Main Airport)', 1.5),
('LHR (London Heathrow)', 'ORY (Paris Orly)', 1.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'JFK (New York John F. Kennedy)', 1.1),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 3.8),
('LHR (London Heathrow)', 'FRA (Frankfurt am Main Airport)', 3.2),
('JFK (New York John F. Kennedy)', 'SIN (Singapore Changi Airport)', 3.6),
('LHR (London Heathrow)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.7),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'AMS (Amsterdam Schiphol)', 2.3),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 1.3),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 3.3),
('DXB (Dubai International Airport)', 'ORY (Paris Orly)', 2.6),
('MAD (Madrid Barajas Airport)', 'JFK (New York John F. Kennedy)', 1.4),
('LHR (London Heathrow)', 'SIN (Singapore Changi Airport)', 1.6),
('MAD (Madrid Barajas Airport)', 'CDG (Paris Charles de Gaulle)', 2.7),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 1.9),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 3.0),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 3.8),
('DXB (Dubai International Airport)', 'SIN (Singapore Changi Airport)', 2.3),
('DXB (Dubai International Airport)', 'SIN (Singapore Changi Airport)', 1.6),
('SIN (Singapore Changi Airport)', 'CDG (Paris Charles de Gaulle)', 2.2),
('MAD (Madrid Barajas Airport)', 'JFK (New York John F. Kennedy)', 1.9),
('JFK (New York John F. Kennedy)', 'LHR (London Heathrow)', 3.6),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 2.8),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 2.3),
('CDG (Paris Charles de Gaulle)', 'DXB (Dubai International Airport)', 3.6),
('FRA (Frankfurt am Main Airport)', 'AMS (Amsterdam Schiphol)', 1.0),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 3.5),
('ORY (Paris Orly)', 'MAD (Madrid Barajas Airport)', 2.7),
('LHR (London Heathrow)', 'CDG (Paris Charles de Gaulle)', 3.3),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 1.5),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 3.1),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 2.4),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'SIN (Singapore Changi Airport)', 3.9),
('FRA (Frankfurt am Main Airport)', 'ORY (Paris Orly)', 2.7),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 1.6),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 1.6),
('ORY (Paris Orly)', 'CDG (Paris Charles de Gaulle)', 3.1),
('MAD (Madrid Barajas Airport)', 'ORY (Paris Orly)', 2.0),
('MAD (Madrid Barajas Airport)', 'SIN (Singapore Changi Airport)', 1.5),
('DXB (Dubai International Airport)', 'MAD (Madrid Barajas Airport)', 1.9),
('DXB (Dubai International Airport)', 'FRA (Frankfurt am Main Airport)', 3.5),
('SIN (Singapore Changi Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 1.6),
('JFK (New York John F. Kennedy)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.0),
('MAD (Madrid Barajas Airport)', 'AMS (Amsterdam Schiphol)', 1.2),
('ORY (Paris Orly)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 2.6),
('JFK (New York John F. Kennedy)', 'LHR (London Heathrow)', 3.1),
('SIN (Singapore Changi Airport)', 'MAD (Madrid Barajas Airport)', 1.0),
('CDG (Paris Charles de Gaulle)', 'AMS (Amsterdam Schiphol)', 3.4),
('MAD (Madrid Barajas Airport)', 'CDG (Paris Charles de Gaulle)', 2.5),
('FRA (Frankfurt am Main Airport)', 'JFK (New York John F. Kennedy)', 1.6),
('JFK (New York John F. Kennedy)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.6),
('ORY (Paris Orly)', 'JFK (New York John F. Kennedy)', 2.7),
('MAD (Madrid Barajas Airport)', 'DXB (Dubai International Airport)', 1.3),
('FRA (Frankfurt am Main Airport)', 'SIN (Singapore Changi Airport)', 3.2),
('ORY (Paris Orly)', 'SIN (Singapore Changi Airport)', 1.2),
('ORY (Paris Orly)', 'CDG (Paris Charles de Gaulle)', 3.5),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 3.4),
('AMS (Amsterdam Schiphol)', 'SIN (Singapore Changi Airport)', 2.5),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 4.0),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 2.9),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 2.0),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 2.7),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 1.3),
('SIN (Singapore Changi Airport)', 'AMS (Amsterdam Schiphol)', 3.3),
('SIN (Singapore Changi Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 3.5),
('JFK (New York John F. Kennedy)', 'CDG (Paris Charles de Gaulle)', 3.4),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 1.1),
('LHR (London Heathrow)', 'CDG (Paris Charles de Gaulle)', 2.9),
('JFK (New York John F. Kennedy)', 'LHR (London Heathrow)', 1.0),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'ORY (Paris Orly)', 2.1),
('AMS (Amsterdam Schiphol)', 'LHR (London Heathrow)', 2.1),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'CDG (Paris Charles de Gaulle)', 4.0),
('JFK (New York John F. Kennedy)', 'LHR (London Heathrow)', 3.4),
('FRA (Frankfurt am Main Airport)', 'ORY (Paris Orly)', 2.1),
('FRA (Frankfurt am Main Airport)', 'MAD (Madrid Barajas Airport)', 3.1),
('LHR (London Heathrow)', 'CDG (Paris Charles de Gaulle)', 1.2),
('ORY (Paris Orly)', 'DXB (Dubai International Airport)', 1.9),
('SIN (Singapore Changi Airport)', 'JFK (New York John F. Kennedy)', 2.5),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 3.1),
('MAD (Madrid Barajas Airport)', 'LHR (London Heathrow)', 1.6),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 3.5),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'JFK (New York John F. Kennedy)', 3.1),
('AMS (Amsterdam Schiphol)', 'LHR (London Heathrow)', 3.0),
('SIN (Singapore Changi Airport)', 'ORY (Paris Orly)', 2.6),
('MAD (Madrid Barajas Airport)', 'AMS (Amsterdam Schiphol)', 2.1),
('CDG (Paris Charles de Gaulle)', 'DXB (Dubai International Airport)', 2.5),
('LHR (London Heathrow)', 'ORY (Paris Orly)', 3.8),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 2.8),
('LHR (London Heathrow)', 'SIN (Singapore Changi Airport)', 1.1),
('MAD (Madrid Barajas Airport)', 'LHR (London Heathrow)', 7.5),
('DXB (Dubai International Airport)', 'AMS (Amsterdam Schiphol)', 7.6),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 11.4),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'CDG (Paris Charles de Gaulle)', 11.2),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 7.7),
('FRA (Frankfurt am Main Airport)', 'CDG (Paris Charles de Gaulle)', 11.2),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'AMS (Amsterdam Schiphol)', 6.3),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 6.2),
('CDG (Paris Charles de Gaulle)', 'MAD (Madrid Barajas Airport)', 7.6),
('LHR (London Heathrow)', 'CDG (Paris Charles de Gaulle)', 8.7),
('AMS (Amsterdam Schiphol)', 'DXB (Dubai International Airport)', 11.8),
('FRA (Frankfurt am Main Airport)', 'MAD (Madrid Barajas Airport)', 8.7),
('FRA (Frankfurt am Main Airport)', 'SIN (Singapore Changi Airport)', 8.6),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 7.1),
('FRA (Frankfurt am Main Airport)', 'CDG (Paris Charles de Gaulle)', 9.1),
('LHR (London Heathrow)', 'FRA (Frankfurt am Main Airport)', 6.7),
('AMS (Amsterdam Schiphol)', 'DXB (Dubai International Airport)', 8.1),
('SIN (Singapore Changi Airport)', 'FRA (Frankfurt am Main Airport)', 8.6),
('AMS (Amsterdam Schiphol)', 'FRA (Frankfurt am Main Airport)', 11.0),
('ORY (Paris Orly)', 'AMS (Amsterdam Schiphol)', 6.2),
('DXB (Dubai International Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 6.9),
('SIN (Singapore Changi Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 10.8),
('DXB (Dubai International Airport)', 'CDG (Paris Charles de Gaulle)', 10.4),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'LHR (London Heathrow)', 6.5),
('CDG (Paris Charles de Gaulle)', 'DXB (Dubai International Airport)', 10.4),
('CDG (Paris Charles de Gaulle)', 'DXB (Dubai International Airport)', 7.9),
('JFK (New York John F. Kennedy)', 'MAD (Madrid Barajas Airport)', 6.8),
('JFK (New York John F. Kennedy)', 'MAD (Madrid Barajas Airport)', 6.3),
('SIN (Singapore Changi Airport)', 'FRA (Frankfurt am Main Airport)', 7.3),
('ORY (Paris Orly)', 'DXB (Dubai International Airport)', 9.6),
('MAD (Madrid Barajas Airport)', 'JFK (New York John F. Kennedy)', 7.9),
('JFK (New York John F. Kennedy)', 'ORY (Paris Orly)', 6.8),
('JFK (New York John F. Kennedy)', 'MAD (Madrid Barajas Airport)', 10.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'AMS (Amsterdam Schiphol)', 6.4),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 9.8),
('MAD (Madrid Barajas Airport)', 'CDG (Paris Charles de Gaulle)', 6.3),
('SIN (Singapore Changi Airport)', 'CDG (Paris Charles de Gaulle)', 8.2),
('ORY (Paris Orly)', 'SIN (Singapore Changi Airport)', 8.9),
('DXB (Dubai International Airport)', 'JFK (New York John F. Kennedy)', 6.6),
('FRA (Frankfurt am Main Airport)', 'MAD (Madrid Barajas Airport)', 10.0),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'MAD (Madrid Barajas Airport)', 11.6),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 6.1),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 7.2),
('JFK (New York John F. Kennedy)', 'LHR (London Heathrow)', 6.7),
('SIN (Singapore Changi Airport)', 'JFK (New York John F. Kennedy)', 6.4),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 9.2),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 11.9),
('FRA (Frankfurt am Main Airport)', 'MAD (Madrid Barajas Airport)', 10.8),
('CDG (Paris Charles de Gaulle)', 'ORY (Paris Orly)', 10.9),
('JFK (New York John F. Kennedy)', 'AMS (Amsterdam Schiphol)', 8.6),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 8.8),
('JFK (New York John F. Kennedy)', 'SIN (Singapore Changi Airport)', 6.1),
('ORY (Paris Orly)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 6.8),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 8.3),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'FRA (Frankfurt am Main Airport)', 8.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'ORY (Paris Orly)', 7.1),
('MAD (Madrid Barajas Airport)', 'SIN (Singapore Changi Airport)', 9.1),
('LHR (London Heathrow)', 'MAD (Madrid Barajas Airport)', 10.4),
('DXB (Dubai International Airport)', 'AMS (Amsterdam Schiphol)', 8.8),
('SIN (Singapore Changi Airport)', 'ORY (Paris Orly)', 10.3),
('MAD (Madrid Barajas Airport)', 'FRA (Frankfurt am Main Airport)', 11.9),
('ORY (Paris Orly)', 'AMS (Amsterdam Schiphol)', 9.9),
('CDG (Paris Charles de Gaulle)', 'SIN (Singapore Changi Airport)', 6.8),
('MAD (Madrid Barajas Airport)', 'ORY (Paris Orly)', 11.4),
('JFK (New York John F. Kennedy)', 'AMS (Amsterdam Schiphol)', 8.6),
('SIN (Singapore Changi Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 11.1),
('SIN (Singapore Changi Airport)', 'ORY (Paris Orly)', 8.1),
('AMS (Amsterdam Schiphol)', 'DXB (Dubai International Airport)', 10.7),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 10.8),
('AMS (Amsterdam Schiphol)', 'SIN (Singapore Changi Airport)', 9.4),
('ORY (Paris Orly)', 'LHR (London Heathrow)', 7.0),
('JFK (New York John F. Kennedy)', 'SIN (Singapore Changi Airport)', 9.8),
('FRA (Frankfurt am Main Airport)', 'ORY (Paris Orly)', 6.8),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 8.1),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'AMS (Amsterdam Schiphol)', 7.0),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'CDG (Paris Charles de Gaulle)', 6.3),
('SIN (Singapore Changi Airport)', 'AMS (Amsterdam Schiphol)', 11.5),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 10.4),
('AMS (Amsterdam Schiphol)', 'ORY (Paris Orly)', 6.0),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'JFK (New York John F. Kennedy)', 6.1),
('FRA (Frankfurt am Main Airport)', 'ORY (Paris Orly)', 6.1),
('MAD (Madrid Barajas Airport)', 'LHR (London Heathrow)', 8.1),
('FRA (Frankfurt am Main Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 6.1),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'MAD (Madrid Barajas Airport)', 11.3),
('FRA (Frankfurt am Main Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 8.6),
('AMS (Amsterdam Schiphol)', 'SIN (Singapore Changi Airport)', 7.7),
('JFK (New York John F. Kennedy)', 'LHR (London Heathrow)', 9.9),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 10.5),
('DXB (Dubai International Airport)', 'AMS (Amsterdam Schiphol)', 10.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'ORY (Paris Orly)', 7.0),
('ORY (Paris Orly)', 'LHR (London Heathrow)', 10.4),
('CDG (Paris Charles de Gaulle)', 'MAD (Madrid Barajas Airport)', 8.9),
('JFK (New York John F. Kennedy)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 10.7),
('MAD (Madrid Barajas Airport)', 'SIN (Singapore Changi Airport)', 10.9),
('SIN (Singapore Changi Airport)', 'FRA (Frankfurt am Main Airport)', 11.3),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 7.8),
('LHR (London Heathrow)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 10.6),
('ORY (Paris Orly)', 'CDG (Paris Charles de Gaulle)', 7.1),
('CDG (Paris Charles de Gaulle)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 10.8),
('MAD (Madrid Barajas Airport)', 'CDG (Paris Charles de Gaulle)', 7.4),
('CDG (Paris Charles de Gaulle)', 'MAD (Madrid Barajas Airport)', 9.8),
('FRA (Frankfurt am Main Airport)', 'MAD (Madrid Barajas Airport)', 10.3),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 9.1),
('DXB (Dubai International Airport)', 'ORY (Paris Orly)', 8.7),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 11.9),
('ORY (Paris Orly)', 'DXB (Dubai International Airport)', 7.6),
('LHR (London Heathrow)', 'AMS (Amsterdam Schiphol)', 9.0),
('LHR (London Heathrow)', 'MAD (Madrid Barajas Airport)', 10.6),
('SIN (Singapore Changi Airport)', 'LHR (London Heathrow)', 10.4),
('ORY (Paris Orly)', 'JFK (New York John F. Kennedy)', 11.4),
('LHR (London Heathrow)', 'SIN (Singapore Changi Airport)', 9.6),
('LHR (London Heathrow)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 8.2),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 11.9),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 11.2),
('DXB (Dubai International Airport)', 'SIN (Singapore Changi Airport)', 10.9),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'SIN (Singapore Changi Airport)', 6.8),
('ORY (Paris Orly)', 'FRA (Frankfurt am Main Airport)', 8.5),
('DXB (Dubai International Airport)', 'AMS (Amsterdam Schiphol)', 9.6),
('AMS (Amsterdam Schiphol)', 'ORY (Paris Orly)', 11.8),
('JFK (New York John F. Kennedy)', 'AMS (Amsterdam Schiphol)', 9.9),
('JFK (New York John F. Kennedy)', 'DXB (Dubai International Airport)', 7.0),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 7.3),
('DXB (Dubai International Airport)', 'JFK (New York John F. Kennedy)', 6.4),
('SIN (Singapore Changi Airport)', 'CDG (Paris Charles de Gaulle)', 8.6),
('AMS (Amsterdam Schiphol)', 'MAD (Madrid Barajas Airport)', 9.9),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'ORY (Paris Orly)', 6.8),
('MAD (Madrid Barajas Airport)', 'CDG (Paris Charles de Gaulle)', 7.3),
('AMS (Amsterdam Schiphol)', 'LHR (London Heathrow)', 9.3),
('MAD (Madrid Barajas Airport)', 'DXB (Dubai International Airport)', 8.0),
('CDG (Paris Charles de Gaulle)', 'LHR (London Heathrow)', 10.8),
('SIN (Singapore Changi Airport)', 'JFK (New York John F. Kennedy)', 9.9),
('AMS (Amsterdam Schiphol)', 'CDG (Paris Charles de Gaulle)', 7.0),
('SIN (Singapore Changi Airport)', 'CDG (Paris Charles de Gaulle)', 11.6),
('SIN (Singapore Changi Airport)', 'AMS (Amsterdam Schiphol)', 7.4),
('MAD (Madrid Barajas Airport)', 'FRA (Frankfurt am Main Airport)', 8.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'JFK (New York John F. Kennedy)', 8.4),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'CDG (Paris Charles de Gaulle)', 8.2),
('JFK (New York John F. Kennedy)', 'CDG (Paris Charles de Gaulle)', 9.3),
('AMS (Amsterdam Schiphol)', 'JFK (New York John F. Kennedy)', 9.8),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 9.9),
('AMS (Amsterdam Schiphol)', 'LHR (London Heathrow)', 8.8),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'CDG (Paris Charles de Gaulle)', 9.3),
('JFK (New York John F. Kennedy)', 'DXB (Dubai International Airport)', 9.3),
('CDG (Paris Charles de Gaulle)', 'DXB (Dubai International Airport)', 10.2),
('FRA (Frankfurt am Main Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 10.3),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 7.7),
('CDG (Paris Charles de Gaulle)', 'FRA (Frankfurt am Main Airport)', 7.7),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'AMS (Amsterdam Schiphol)', 10.4),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'JFK (New York John F. Kennedy)', 10.8),
('LHR (London Heathrow)', 'CDG (Paris Charles de Gaulle)', 7.9),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 6.9),
('DXB (Dubai International Airport)', 'LHR (London Heathrow)', 8.7),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'FRA (Frankfurt am Main Airport)', 8.2),
('SIN (Singapore Changi Airport)', 'JFK (New York John F. Kennedy)', 10.3),
('LHR (London Heathrow)', 'DXB (Dubai International Airport)', 9.6),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'SIN (Singapore Changi Airport)', 11.5),
('SIN (Singapore Changi Airport)', 'CDG (Paris Charles de Gaulle)', 7.6),
('DXB (Dubai International Airport)', 'ORY (Paris Orly)', 11.2),
('DXB (Dubai International Airport)', 'MAD (Madrid Barajas Airport)', 7.4),
('FRA (Frankfurt am Main Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 11.0),
('ORY (Paris Orly)', 'SIN (Singapore Changi Airport)', 9.1),
('LHR (London Heathrow)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 6.5),
('SIN (Singapore Changi Airport)', 'DXB (Dubai International Airport)', 8.3),
('CDG (Paris Charles de Gaulle)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 8.0),
('FRA (Frankfurt am Main Airport)', 'LHR (London Heathrow)', 9.6),
('LHR (London Heathrow)', 'ORY (Paris Orly)', 9.3),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'DXB (Dubai International Airport)', 9.0),
('CDG (Paris Charles de Gaulle)', 'JFK (New York John F. Kennedy)', 11.4),
('FRA (Frankfurt am Main Airport)', 'LHR (London Heathrow)', 11.4),
('LHR (London Heathrow)', 'JFK (New York John F. Kennedy)', 10.4),
('IST (Istanbul Sabiha Gökçen Havalimanı)', 'MAD (Madrid Barajas Airport)', 8.3),
('LHR (London Heathrow)', 'SIN (Singapore Changi Airport)', 10.0),
('MAD (Madrid Barajas Airport)', 'IST (Istanbul Sabiha Gökçen Havalimanı)', 8.9),
('FRA (Frankfurt am Main Airport)', 'LHR (London Heathrow)', 8.5),
('FRA (Frankfurt am Main Airport)', 'MAD (Madrid Barajas Airport)', 10.7);